name    'inkblot/shorewall'
version '4.5.2'
source  'git://github.com/inkblot/puppet-shorewall'
author  'inkblot'
license 'Apache 2.0'
summary 'Shorewall Firewall'
description 'A Puppet module to install and configure a Shorewall firewall'
project_page 'https://github.com/inkblot/puppet-shorewall'

dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
